version: "3.9"
services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.redirect-www.rule=Host(`www.${DOMAIN_NAME}`)"
      - "traefik.http.routers.redirect-www.entrypoints=websecure"
      - "traefik.http.routers.redirect-www.tls.certresolver=myresolver"
      - "traefik.http.middlewares.redirect-to-root.redirectregex.regex=^https://www\\.(.*)$$"
      - "traefik.http.middlewares.redirect-to-root.redirectregex.replacement=https://$$1"
      - "traefik.http.routers.redirect-www.middlewares=redirect-to-root@docker"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    container_name: frontend
    restart: always
    environment:
      - PORT=8080
      - AUTH_API_ADDRESS=http://auth-api:8081
      - TODOS_API_ADDRESS=http://todos-api:8082
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"

  auth-api:
    build:
      context: ./auth-api
      dockerfile: Dockerfile-auth-api
    container_name: auth-api
    restart: always
    environment:
      - AUTH_API_PORT=8081
      - USERS_API_ADDRESS=${USERS_API_ADDRESS}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - users-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-api.rule=Host(`auth.${DOMAIN_NAME}`)"
      - "traefik.http.routers.auth-api.entrypoints=websecure"
      - "traefik.http.routers.auth-api.tls.certresolver=myresolver"
      - "traefik.http.services.auth-api.loadbalancer.server.port=8081"

  todos-api:
    build:
      context: ./todos-api
      dockerfile: Dockerfile-todos-api
    container_name: todos-api
    restart: always
    environment:
      - TODO_API_PORT=8082
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CHANNEL=${REDIS_CHANNEL}
    depends_on:
      - redis-queue
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todos-api.rule=Host(`todos.${DOMAIN_NAME}`)"
      - "traefik.http.routers.todos-api.entrypoints=websecure"
      - "traefik.http.routers.todos-api.tls.certresolver=myresolver"
      - "traefik.http.services.todos-api.loadbalancer.server.port=8082"

  users-api:
    build:
      context: ./users-api
      dockerfile: Dockerfile-users-api
    container_name: users-api
    restart: always
    environment:
      - SERVER_PORT=8083
      - JWT_SECRET=${JWT_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users-api.rule=Host(`users.${DOMAIN_NAME}`)"
      - "traefik.http.routers.users-api.entrypoints=websecure"
      - "traefik.http.routers.users-api.tls.certresolver=myresolver"
      - "traefik.http.services.users-api.loadbalancer.server.port=8083"

  log-message-processor:
    build:
      context: ./log-message-processor
      dockerfile: Dockerfile-log-message-processor
    container_name: log-message-processor
    restart: always
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CHANNEL=${REDIS_CHANNEL}
    depends_on:
      - redis-queue

  redis-queue:
    image: redis:alpine
    container_name: redis-queue
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: traefik-network
    driver: bridge